# Use a base image for Python
FROM python:latest

# Set the working directory inside the container
WORKDIR /app

# Copy the Python script into the container
COPY . .

# Command to run the Python script
CMD ["python", "Solution.py"]
