# Use a base image for Go
FROM golang:latest

# Set the working directory inside the container
WORKDIR /app

# Copy the Go source file into the container
COPY Solution.go .

# Command to run the Go program
CMD ["go", "run", "Solution.go"]
