# Use a base image for Ruby
FROM ruby:latest

# Set the working directory inside the container
WORKDIR /app

# Copy the Ruby source code into the container
COPY . .

# Command to run the Ruby program
CMD ["ruby", "Solution.rb"]
