# Use a base image for PHP
FROM php:latest

# Set the working directory inside the container
WORKDIR /app

# Copy the PHP script into the container
COPY . .

# Command to run the PHP script
CMD ["php", "Solution.php"]
