# Use a base image for Node.js
FROM node:14-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy the JavaScript source file into the container
COPY . .

# Command to run the JavaScript program
CMD ["node", "Solution.js"]
